/*
 * Automatically generated by jrpcgen 1.0.6 on 14/01/06 17:53
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package jrds.probe.rstat;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

/**
 * The class <code>rstatClient</code> implements the client stub proxy
 * for the RSTATPROG remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class rstatClient extends OncRpcClientStub {

    /**
     * Constructs a <code>rstatClient</code> client stub proxy object
     * from which the RSTATPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rstatClient(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, rstat.RSTATPROG, 4, 0, protocol);
    }

    /**
     * Constructs a <code>rstatClient</code> client stub proxy object
     * from which the RSTATPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rstatClient(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, rstat.RSTATPROG, 4, port, protocol);
    }

    /**
     * Constructs a <code>rstatClient</code> client stub proxy object
     * from which the RSTATPROG remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rstatClient(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>rstatClient</code> client stub proxy object
     * from which the RSTATPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rstatClient(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>rstatClient</code> client stub proxy object
     * from which the RSTATPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rstatClient(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure RSTATPROC_STATS_4.
     * @return Result from remote procedure call (of type statsvar).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public statsvar RSTATPROC_STATS_4()
           throws OncRpcException, IOException {
        XdrVoid args$ = XdrVoid.XDR_VOID;
        statsvar result$ = new statsvar();
        client.call(rstat.RSTATPROC_STATS_4, rstat.RSTATVERS_VAR, args$, result$);
        return result$;
    }

    /**
     * Call remote procedure RSTATPROC_HAVEDISK_4.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int RSTATPROC_HAVEDISK_4()
           throws OncRpcException, IOException {
        XdrVoid args$ = XdrVoid.XDR_VOID;
        XdrInt result$ = new XdrInt();
        client.call(rstat.RSTATPROC_HAVEDISK_4, rstat.RSTATVERS_VAR, args$, result$);
        return result$.intValue();
    }

    /**
     * Call remote procedure RSTATPROC_STATS_3.
     * @return Result from remote procedure call (of type statstime).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public statstime RSTATPROC_STATS_3()
           throws OncRpcException, IOException {
        XdrVoid args$ = XdrVoid.XDR_VOID;
        statstime result$ = new statstime();
        client.call(rstat.RSTATPROC_STATS_3, rstat.RSTATVERS_TIME, args$, result$);
        return result$;
    }

    /**
     * Call remote procedure RSTATPROC_HAVEDISK_3.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int RSTATPROC_HAVEDISK_3()
           throws OncRpcException, IOException {
        XdrVoid args$ = XdrVoid.XDR_VOID;
        XdrInt result$ = new XdrInt();
        client.call(rstat.RSTATPROC_HAVEDISK_3, rstat.RSTATVERS_TIME, args$, result$);
        return result$.intValue();
    }

}
// End of rstatClient.java
