/*
 * Automatically generated by jrpcgen 1.0.6 on 14/01/06 17:02
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class rstat_timeval implements XdrAble {
    public int tv_sec;
    public int tv_usec;

    public rstat_timeval() {
    }

    public rstat_timeval(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(tv_sec);
        xdr.xdrEncodeInt(tv_usec);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        tv_sec = xdr.xdrDecodeInt();
        tv_usec = xdr.xdrDecodeInt();
    }

}
// End of rstat_timeval.java
