/*
 * Automatically generated by jrpcgen 1.0.6 on 14/01/06 17:02
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * A collection of constants used by the "rstat" ONC/RPC program.
 */
public interface rstat {
    public static final int RSTATPROC_HAVEDISK_3 = 2;
    public static final int RSTATVERS_SWTCH = 2;
    public static final int RSTATPROC_HAVEDISK_2 = 2;
    public static final int RSTATPROC_HAVEDISK_1 = 2;
    public static final int RSTATPROG = 100001;
    public static final int DK_NDRIVE = 4;
    public static final int RSTATVERS_ORIG = 1;
    public static final int CPUSTATES = 4;
    public static final int RSTATPROC_STATS_3 = 1;
    public static final int RSTATPROC_STATS_2 = 1;
    public static final int RSTATPROC_STATS_1 = 1;
    public static final int RSTATVERS_TIME = 3;
}
// End of rstat.java
