/*
 * Automatically generated by jrpcgen 1.0.6 on 14/01/06 17:53
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package jrds.probe.rstat;
/**
 * A collection of constants used by the "rstat" ONC/RPC program.
 */
public interface rstat {
    public static final int RSTATPROC_HAVEDISK_3 = 2;
    public static final int RSTATPROG = 100001;
    public static final int RSTAT_CPU_USER = 0;
    public static final int RSTAT_CPU_NICE = 1;
    public static final int RSTATPROC_STATS_4 = 1;
    public static final int RSTATPROC_STATS_3 = 1;
    public static final int RSTATVERS_TIME = 3;
    public static final int RSTAT_CPU_SYS = 2;
    public static final int RSTAT_DK_NDRIVE = 4;
    public static final int RSTAT_CPUSTATES = 4;
    public static final int RSTATPROC_HAVEDISK_4 = 2;
    public static final int RSTATVERS_VAR = 4;
    public static final int RSTAT_CPU_IDLE = 3;
}
// End of rstat.java
